name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: copy via ssh
        uses: appleboy/scp-action@master
        with:
          host: '${{ secrets.HOST }}'
          username: '${{ secrets.USERNAME }}'
          key: '${{ secrets.KEY }}'
          port: 22
          source: .,!node_modules
          target: ~/anon_curhat
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.HOST }}'
          username: '${{ secrets.USERNAME }}'
          key: '${{ secrets.KEY }}'
          port: 2
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/anon_curhat/front-end
            npm install
            cd ~/anon_curhat/back-end
            npm install
            pm2 restart all
